[package]

name = "usb"
version = "0.1.1"
authors = [ "Kevin Mehall <km@kevinmehall.net>", "Ian Daniher <it.daniher@gmail.com>" ]
description = "Library for low-level access to USB devices via libusb"
license = "MIT"
keywords = ["USB", "hardware", "bindings"]

[lib]
name = "usb"
